SELECT DATE_FORMAT(OS.SALES_DATE,'%Y') AS YEAR, DATE_FORMAT(OS.SALES_DATE,'%m') AS MONTH, UI.GENDER, COUNT(DISTINCT OS.USER_ID) AS USER
FROM USER_INFO UI
JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE 1=1
GROUP BY YEAR,MONTH,GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR,MONTH,GENDER;
