# WITH RECURSIVE RECUR AS(
#     SELECT 0 AS N
#     UNION ALL
#     SELECT N + 1
#     FROM RECUR
#     WHERE N<23
# )
# SELECT
# R.N AS HOUR, CASE WHEN A.COUNT IS NOT NULL THEN A.COUNT ELSE 0 END AS COUNT
# FROM
# (SELECT HOUR(DATETIME) AS HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# HAVING HOUR BETWEEN '0' AND '23'
# ORDER BY HOUR)A
# RIGHT OUTER JOIN RECUR R
# ON A.HOUR = R.N;


WITH RECURSIVE RECUR AS(
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1
    FROM RECUR
    WHERE N<23
)

SELECT N AS HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT OUTER JOIN RECUR R
ON HOUR(A.DATETIME) = R.N
GROUP BY N
HAVING HOUR BETWEEN '0' AND '23'
ORDER BY N;