SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE 1=1
AND ITEM_ID NOT IN (SELECT DISTINCT IT1.ITEM_ID
    FROM ITEM_TREE IT1
    JOIN ITEM_TREE IT2
    ON IT1.ITEM_ID = IT2.PARENT_ITEM_ID)
ORDER BY 1 DESC