-- FOOD_ORDER  -> PRODUCE_DATE = 2022-5
WITH MAY_ORDER AS (
    SELECT FO.*, FP.PRODUCT_NAME ,FP.PRICE*FO.AMOUNT TOTAL_SALES
    FROM FOOD_ORDER FO
    JOIN FOOD_PRODUCT FP
    ON FO.PRODUCT_ID = FP.PRODUCT_ID
    WHERE 1=1
    AND DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05' 
)

SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL_SALES) TOTAL_SALES
FROM  MAY_ORDER
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID